name: food_ordering_system
description: A Flutter project for a food ordering system.

publish_to: 'none' # Remove this line if you plan to publish your package.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
